package com.nortal.race.assignment.model;

import java.io.Serializable;

/**
 * Created by Priit Liivak
 */
public enum ThrusterLevel implements Serializable {

    T0(0),
    T1(1),
    T2(2),
    T3(3),
    T4(4);

    /**
     * Push force equivalent to acceleration m/s² that is generated for given Thrust level
     * <p>
     * Pure acceleration output of thrusters.
     * Not considering drag generated by the environment.
     */
    private double acceleration;

    ThrusterLevel(double acceleration) {
        this.acceleration = acceleration;
    }

    public double getAcceleration() {
        return acceleration;
    }
}
